import { CURRENT_SCHEMA_VERSION, ProgramFile } from '@/types/program';

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  data?: ProgramFile;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

const MEAL_TYPES = ['breakfast', 'lunch', 'dinner', 'snack', 'custom'];

/**
 * Validates a raw parsed JSON value against the ForgeWorkout program
 * schema. Designed to give specific, human-readable errors so a bad
 * import file is easy to fix (including files generated by AI models).
 */
export function validateProgramFile(raw: unknown): ValidationResult {
  const errors: string[] = [];

  if (!isObject(raw)) {
    return { valid: false, errors: ['The file is not a JSON object.'] };
  }

  const schemaVersion = raw['schemaVersion'];
  if (typeof schemaVersion !== 'number') {
    errors.push('"schemaVersion" must be a number.');
  } else if (schemaVersion > CURRENT_SCHEMA_VERSION) {
    errors.push(
      `"schemaVersion" (${schemaVersion}) is newer than this app supports (${CURRENT_SCHEMA_VERSION}). Update the app.`,
    );
  }

  const meta = raw['meta'];
  if (!isObject(meta)) {
    errors.push('"meta" is required and must be an object.');
  } else {
    if (typeof meta['name'] !== 'string' || !meta['name'].trim()) {
      errors.push('"meta.name" is required and must be a non-empty string.');
    }
    if (
      typeof meta['durationDays'] !== 'number' ||
      meta['durationDays'] <= 0 ||
      !Number.isInteger(meta['durationDays'])
    ) {
      errors.push('"meta.durationDays" is required and must be a positive integer.');
    }
    if (
      meta['targetCalories'] !== undefined &&
      typeof meta['targetCalories'] !== 'number'
    ) {
      errors.push('"meta.targetCalories" must be a number if provided.');
    }
    if (
      meta['targetProtein'] !== undefined &&
      typeof meta['targetProtein'] !== 'number'
    ) {
      errors.push('"meta.targetProtein" must be a number if provided.');
    }
    if (meta['startDate'] !== undefined) {
      if (
        typeof meta['startDate'] !== 'string' ||
        !/^\d{4}-\d{2}-\d{2}$/.test(meta['startDate'])
      ) {
        errors.push('"meta.startDate" must be a "yyyy-mm-dd" string if provided.');
      }
    }
  }

  const days = raw['days'];
  if (!Array.isArray(days) || days.length === 0) {
    errors.push('"days" is required and must be a non-empty array.');
  } else {
    const seenDayNumbers = new Set<number>();
    days.forEach((day, index) => {
      const prefix = `days[${index}]`;
      if (!isObject(day)) {
        errors.push(`${prefix} must be an object.`);
        return;
      }
      if (
        typeof day['day'] !== 'number' ||
        !Number.isInteger(day['day']) ||
        day['day'] <= 0
      ) {
        errors.push(`${prefix}.day must be a positive integer.`);
      } else if (seenDayNumbers.has(day['day'])) {
        errors.push(`${prefix}.day (${day['day']}) is duplicated.`);
      } else {
        seenDayNumbers.add(day['day']);
      }

      if (day['isRestDay'] !== undefined && typeof day['isRestDay'] !== 'boolean') {
        errors.push(`${prefix}.isRestDay must be a boolean if provided.`);
      }

      const workout = day['workout'];
      if (workout !== undefined && workout !== null) {
        if (!isObject(workout)) {
          errors.push(`${prefix}.workout must be an object or null.`);
        } else {
          if (typeof workout['title'] !== 'string' || !workout['title'].trim()) {
            errors.push(`${prefix}.workout.title is required.`);
          }
          if (!Array.isArray(workout['exercises'])) {
            errors.push(`${prefix}.workout.exercises must be an array.`);
          } else {
            workout['exercises'].forEach((exercise, exIndex) => {
              const exPrefix = `${prefix}.workout.exercises[${exIndex}]`;
              if (!isObject(exercise)) {
                errors.push(`${exPrefix} must be an object.`);
                return;
              }
              if (typeof exercise['name'] !== 'string' || !exercise['name'].trim()) {
                errors.push(`${exPrefix}.name is required.`);
              }
              if (typeof exercise['sets'] !== 'number' || exercise['sets'] <= 0) {
                errors.push(`${exPrefix}.sets must be a positive number.`);
              }
              if (typeof exercise['reps'] !== 'string' || !exercise['reps'].trim()) {
                errors.push(`${exPrefix}.reps is required (e.g. "12" or "30s").`);
              }
            });
          }
        }
      }

      const diet = day['diet'];
      if (diet !== undefined && diet !== null) {
        if (!isObject(diet)) {
          errors.push(`${prefix}.diet must be an object or null.`);
        } else if (!Array.isArray(diet['meals'])) {
          errors.push(`${prefix}.diet.meals must be an array.`);
        } else {
          diet['meals'].forEach((meal, mealIndex) => {
            const mealPrefix = `${prefix}.diet.meals[${mealIndex}]`;
            if (!isObject(meal)) {
              errors.push(`${mealPrefix} must be an object.`);
              return;
            }
            if (
              typeof meal['type'] !== 'string' ||
              !MEAL_TYPES.includes(meal['type'])
            ) {
              errors.push(
                `${mealPrefix}.type must be one of ${MEAL_TYPES.join(', ')}.`,
              );
            }
            if (!Array.isArray(meal['items'])) {
              errors.push(`${mealPrefix}.items must be an array.`);
            } else {
              meal['items'].forEach((item, itemIndex) => {
                const itemPrefix = `${mealPrefix}.items[${itemIndex}]`;
                if (!isObject(item)) {
                  errors.push(`${itemPrefix} must be an object.`);
                  return;
                }
                if (typeof item['name'] !== 'string' || !item['name'].trim()) {
                  errors.push(`${itemPrefix}.name is required.`);
                }
                for (const field of ['calories', 'protein', 'carbs', 'fat']) {
                  if (typeof item[field] !== 'number' || item[field] < 0) {
                    errors.push(`${itemPrefix}.${field} must be a non-negative number.`);
                  }
                }
              });
            }
          });
        }
      }
    });
  }

  if (errors.length > 0) {
    return { valid: false, errors };
  }

  return { valid: true, errors: [], data: raw as unknown as ProgramFile };
}
